version: '3'

services:
  bootnode:
    image: ethereum/client-go:release-1.10
    # image: ethereum/client-go:latest
    # image: ethereum/client-go:alltools-latest
    container_name: bootnode
    entrypoint: ["/eth/start.sh"]
    # command: "ping localhost"
    restart: always
    ports:
     - 8545:8545
     - 8546:8546
     - 30303:30303/tcp
     - 30303:30303/udp
    volumes:
     - ${PWD}/eth:/eth
    networks:
     - skynet

  # ethnode:
  #   image: ethereum/client-go:latest
  #   container_name: ethnode
  #   entrypoint: ["echo", "Service disabled"]
  #   depends_on:
  #    - bootnode
  #   environment:
  #     TZ: Asia/Bangkok
  #   ports:
  #     - 8101:8545
  #     - 30101:30303
  #   volumes:
  #     - ${PWD}/eth:/eth
  #   networks:
  #    - skynet

networks:
  skynet:
    driver: bridge
